//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Athi.Whippet.Installer.Framework.Database.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Scripts_PostgreSQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts_PostgreSQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Athi.Whippet.Installer.Framework.Database.ResourceFiles.Scripts_PostgreSQL", typeof(Scripts_PostgreSQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          CREATE DATABASE IF NOT EXISTS &apos;$$WHIPPET$$&apos; /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION=&apos;N&apos; */;
        ///
        ///          CREATE DATABASE $$WHIPPET$$ 
        ///            WITH 
        ///              OWNER = &apos;whippet_sa&apos; 
        ///              ENCODING = &apos;UTF8&apos; 
        ///              LC_COLLATE = &apos;en_US.utf8&apos; 
        ///              LC_CTYPE = &apos;en_US.utf8&apos; 
        ///              LOCALE_PROVIDER = &apos;libc&apos; 
        ///              TABLESPACE = pg_default 
        ///              CONNECTION LIMIT = -1 
        ///              IS_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DB_CREATE {
            get {
                return ResourceManager.GetString("DB_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            CREATE ROLE whippet_sa WITH
        ///              LOGIN
        ///              NOSUPERUSER
        ///              INHERIT
        ///              CREATEDB
        ///              NOCREATEROLE
        ///              NOREPLICATION
        ///              PASSWORD = &apos;$$PASSWORD$$&apos;
        ///          END IF;
        ///        .
        /// </summary>
        public static string DB_LOGIN {
            get {
                return ResourceManager.GetString("DB_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          CREATE SCHEMA whippet
        ///            AUTHORIZATION whippet_sa;          
        ///        .
        /// </summary>
        public static string DB_SCHEMA {
            get {
                return ResourceManager.GetString("DB_SCHEMA", resourceCulture);
            }
        }
    }
}
